### ISSUE TITLE
[TIMER-001] 세트 타이머

### ISSUE THREAD

**Issue by eyo-25** [eyo-25/HIIP_APP#11]
## 요구사항 ID
TIMER-001

## 요구사항
세트 타이머

## 상세 요구사항
- 현재 잔여 시간을 기준으로 세트 타이머 작동
- 세트에 맞게 포커스 타이머, 브레이크 타이머 동작
- 잔여시간 없으면 finish 상태
- 중지하거나 세트 종료시 또는 1분 간격으로 저장

## TODO
- [x] 현재 잔여 시간을 기준으로 세트 타이머 세팅
- [x] 타이머 구동
- [x] 브레이크, 포커스 세트 표기
- [x] 잔여시간 없으면 finish
- [x] 자동/수동 저장
