### ISSUE TITLE
[TIMER-002] 결과 화면

### ISSUE THREAD

**Issue by eyo-25** [eyo-25/HIIP_APP#13]
## 요구사항 ID
TIMER-002

## 요구사항
결과 화면

## 상세 요구사항
- 실패, 성공에 따른 결과 화면 진행률, 평균 성공률, 평균 집중률 표기
- 결과 그래프 표기

## TODO
- [x] 실패, 성공에 따른 결과 화면 진행률, 평균 성공률, 평균 집중률 표기
- [x] 결과 그래프 표기
- [x] 결과 적용 put 요청
