### ISSUE TITLE
[DETAIL_001] 플랜 생성

### ISSUE THREAD

**Issue by eyo-25** [eyo-25/HIIP_APP#5]
## 요구사항 ID
DETAIL_001

## 요구사항
플랜 생성

## 상세 요구사항
- 메모는 1글자 이상, plan 기간은 최대 두달까지 가능
- 집중 세트는 뽀모도로 기본 세트로 세팅

## TODO
- [x] Detail form 작성
- [x] 기본 세트 세팅
- [x] plan post 요청
